### ISSUE TITLE
Question about "replace_feature" of sparse feat

### ISSUE THREAD

**Issue by Terminal-K** [Pointcept/Pointcept#161]
Hi, @Gofinge. 
When I was debugging, I found that the features attribute of sparse_conv_feat did not change after this line:
https://github.com/Pointcept/Pointcept/blob/1dd24a07e3533c414539e0d3b918cf793a30d3ff/pointcept/models/point_transformer_v3/point_transformer_v3m1_base.py#L337
So I looked at the code in the spconv, I noticed that the method "replace_feature" returns a new sparse tensor
![replace_feature](https://github.com/Pointcept/Pointcept/assets/59523614/f13efc40-d2dc-4c3a-83ac-ddeb40f7166c)

https://github.com/traveller59/spconv/blob/125a194d895b1bc3ad6ff907bc72641548397b32/spconv/pytorch/core.py#L198

should this line be changed to the following to make it work?
```python
point.sparse_conv_feat = point.sparse_conv_feat.replace_feature(point.feat)
```

**Comment by Gofinge** [comment]
Yes, you exactly are correct! This is an interesting bug, making PTv3 blocks within an encoding stage look like a dual-branch structure. In this structure, xCPE with sparse conv is more like a positional encoding (not affected by the attention layer). I can not predict the performance after fixing this "bug", and I will ablate it locally and then decide how to handle it.

**Comment by Terminal-K** [comment]
Thx, looking forward to your reply again

**Comment by Gofinge** [comment]
Hi, I check the performance on ScanNet both from scratch and PPT pre-train. The overall performance seems unchanged which is also reasonable as model performance should be more related to scale instead of intrinsic design.
(scratch)
![image](https://github.com/Pointcept/Pointcept/assets/39218229/25783b80-6401-4a9d-a18b-3585d26f4a67)
![image](https://github.com/Pointcept/Pointcept/assets/39218229/44ba305b-13e6-4f5c-acd8-6900949622b4)

(ppt)
![image](https://github.com/Pointcept/Pointcept/assets/39218229/73775f46-a976-479e-aba6-0c07d3546ef8)
![image](https://github.com/Pointcept/Pointcept/assets/39218229/c846c487-86d0-4350-8bf3-eef37fcfad9c)

**Comment by Gofinge** [comment]
I support keeping it and fixing the bug. It is not a skip residual, it is a sync feature operation for our Point data. Without it, the structure can be viewed as follows, which is not the structure described in our paper.:

![image](https://github.com/Pointcept/Pointcept/assets/39218229/3213d2aa-1a42-47a7-9568-861a5e312afa)

I said this bug is interesting as it seems to be more "novel" and more like a positional encoding. Yet experiments show that it doesn't contribute to the performance of PTv3, so it is a meaningless "novelty" and I support classical and simple block structure as described in our paper. Simple is more!

![image](https://github.com/Pointcept/Pointcept/assets/39218229/e87ca0bc-49af-47c7-a9f8-ad26790c04a8)

**Comment by Gofinge** [comment]
Yet, if you want to use the current version of the released weight, you can directly delete it. I will retrain the released weight later.

**Comment by Terminal-K** [comment]
Thank you again for your earnest reply! 
I will try to fix this bug and test again.
